class RatioTabInfo {
  List<String> recitersNames = [
    "Ibrahim Al-Akhdar",
    "Akram Al-Alaqami",
    "Majid Al-Anzi",
    "Malik Shaybah Al-Hamd",
    "Maher Al-Muaiqly",
    "Mohammed Al-Erawi",
    "Mohammed Al-Baraq",
    "Mohammed Al-Tablawi",
    "Mohammed Al-Luhaydan",
    "Mohammed Al-Muhaysini",
    "Mohammed Ayoub",
    "Al-Husseini Al-Izzazi",
    "Mohammed Saleh Alam Shah",
    "Mohammed Jibreel",
    "Mohammed Sidiq Al-Manshawi",
    "Mohammed Abdul-Karim",
    "Mohammed Abdul-Hakim Saeed Al-Abdallah",
    "Mahmoud Khalil Al-Husari",
    "Mahmoud Ali Al-Banna",
    "Adel Al-Kalbani",
    "Musa Bilal",
    "Hussein Al-Sheikh",
    "Ibrahim Al-Jurmaini",
    "Mahmoud Al-Rifa'i",
    "Abdul Rahman Al-Suwaid",
    "Khalid Al-Qahhtani",
    "Abdul Rahman Al-Harbi",
    "Abdul Rahman Al-Eisi",
    "Abdullah Al-Shahat",
    "Abdullah Al-Bukhari",
    "Abdullah Abdul-Rahman",
    "Abdullah Al-Shaibi",
    "Abdullah Al-Shammari",
    "Abdullah Al-Zuhri",
    "Abdullah Al-Bukhari",
    "Abdullah Al-Faqih",
    "Abdullah Al-Asiri",
    "Abdullah Al-Bukhari",
    "Abdullah Al-Bukhari",
    "Abdullah Al-Bukhari",
    "Abdullah Al-Bukhari"
  ];

  List<String> radioNames = [
    "Ibrahim Al-Akhdar",
    "Sheikh Abu Bakr Al-Shatri",
    "Ahmad Bin Ali Al-Ajmy",
    "Ahmad Al-Hawashi",
    "Ahmad Saber",
    "Ahmad Nauina",
    "Akram Al-Alaqami",
    "Idrees Abkr",
    "Al-Zain Mohammad Ahmad",
    "Al-Qari Yaseen",
    "Al-Ayoon Al-Koshi",
    "Tawfiq Al-Sayegh",
    "Jamal Shaker Abdullah",
    "Khaled Al-Qahtani",
    "Khaled Abdul-Kafi",
    "Khalifa Al-Tunaiji",
    "Saad Al-Ghamdi",
    "Saud Al-Shuraim",
    "Sahl Yassin",
    "Zaki Daghistani",
    "Sayeed Ramadan",
    "Shirazad Abdul-Rahman Taher",
    "Saber Abdul-Hakim",
    "Salah Al-Budair",
    "Salah Al-Hashim",
    "Salah Abu Khatir",
    "Adel Ryyan",
    "Abdelbari Al-Thubaiti",
    "Abdelbari Mohammad",
    "Abdul-Basit Abdul-Samad",
    "Abdul-Basit Abdul-Samad",
    "Abdul-Basit Abdul-Samad",
    "Abdul-Rahman Al-Sudais",
    "Abdul-Aziz Al-Ahmad",
    "Abdullah Al-Mattrod",
    "Abdullah Basfer",
    "Abdullah Khayyat",
    "Abdullah Al-Johany",
    "Abdul-Rasheed Soufi",
    "Abdul-Rasheed Soufi",
    "Abdul-Mohsin Al-Harthy",
    "Abdul-Mohsin Al-Qasim",
    "Abdul-Mohsin Al-Obaikan",
    "Abdul-Hadi Kanakeri",
    "Abdul-Wadood Haneef",
    "Ali Al-Huthaifi",
    "Ali Jaber",
    "Ali Hajjaj Al-Souasi",
    "Emad Zahir Hafiz",
    "Omar Al-Qazabri",
    "Fares Abbad",
    "Nasser Al-Qatami",
    "Nabil Al-Rifai",
    "Neamah Al-Hassan",
    "Hani Al-Rifai",
    "Waleed Al-Naehi",
    "Yasser Al-Dosari",
    "Yasser Al-Qurashi",
    "Yasser Al-Mazroui",
    "Yahya Hawwa",
    "Yousef Al-Shuaey",
    "Maher Al-Muaiqly",
    "Mohammad Al-Tablawi",
    "Mohammed Al-Luhaydan",
    "Mohammed Ayoub",
    "Mohammad Saleh Alam Shah",
    "Mohammed Jibreel",
    "Mohammed Sidiq Al-Manshawi",
    "Mohammed Sidiq Al-Manshawi",
    "Mohammad Abdul-Karim",
    "Mohammad Abdul-Hakim Abdullah",
    "Mohammad Abdul-Hakim Abdullah",
    "Mahmoud Khalil Al-Husari",
    "Mahmoud Khalil Al-Husari",
    "Mahmoud Khalil Al-Husari",
    "Mahmoud Ali Al-Banna",
    "Mahmoud Ali Al-Banna",
    "Mishary Alafasi",
    "Mustafa Ismail",
    "Mustafa Allahoni",
    "Mustafa Raad Al-Azawy",
    "Muftah Al-Saltany",
    "Maher Shakhashero",
    "Mahmood Al-Sheimy",
    "Khalid Al-Mohana",
    "Adel Al-Khalbany",
    "Mousa Bilal",
    "Hatem Fareed Al-Waer",
    "Mahmood Al-Rifai",
    "Ibrahim Al-Dosari",
    "Muftah Al-Saltany",
    "Jamaan Al-Osaimi",
    "Muftah Al-Saltany",
    "Yousef Bin Noah Ahmad",
    "Muftah Al-Saltany",
    "Moeedh Al-Harthi",
    "Mohammad Rashad Al-Shareef",
    "Ahmad Khader Al-Tarabulsi",
    "Ahmad Al-Tarabulsi",
    "Abdullah Al-Kandari",
    "Ahmad Amer",
    "Mohammed Osman Khan",
    "Al-Dokali Mohammad Al-Alim",
    "Mohammad Abdul-Karim",
    "Al-Fateh Mohammad Al-Zubair",
    "Tariq Abdul-Ghani Daawob",
    "General Broadcasting",
    "Khushiyat Khushiyat",
    "Eid Takbirat",
    "Abdul-Rahman Al-Majed",
    "Fatwa",
    "Ruqyah Sharia",
    "Surah Al-Baqarah",
    "Tafseer of the Holy Quran",
    "Khalid Al-Jileel",
    "Nasser Al-Majed",
    "Hitham Al-Jadani",
    "Ahmad Khalil Shaheen",
    "Abdullah Al-Mousa",
    "Abdullah Al-Khalaf",
    "Majed Al-Zamel",
    "Bandar Balilah",
    "Nasser Al-Osfor",
    "Mohammed Ayoub",
    "Ahmad Deiban",
    "Mohammed Abusneineh",
    "Mohammed Al-Ameen Qeniwa",
    "Abdul-Rahman Al-Shahat",
    "Abdul-Aziz Al-Sheim",
    "Sakeenah",
    "Sahabah",
    "Athkar Sabah",
    "Athkar Masa",
  ];
}
